### ISSUE TITLE
psutil compatibility issue in gaffer==0.5.2

### ISSUE THREAD

**Issue by Ashald** [benoitc/gaffer#60]
```bash
$ pip install gaffer
...
Successfully built gaffer pyuv psutil tornado colorama setproctitle
Installing collected packages: pyuv, psutil, tornado, colorama, setproctitle, gaffer
Successfully installed colorama-0.3.3 gaffer-0.5.2 psutil-3.0.1 pyuv-1.1.0 setproctitle-1.1.8 tornado-2.4.1
```
So far so good. Trying things out...
```bash
$ gaffer --version
Traceback (most recent call last):
  File "/tmp/ashald/.venvs/tmp-17f0a3d67a1d4821/bin/gaffer", line 7, in <module>
    from gaffer.cli.main import main
  File "/tmp/ashald/.venvs/tmp-17f0a3d67a1d4821/lib/python2.7/site-packages/gaffer/cli/main.py", line 40, in <module>
    from ..httpclient import Server, GafferUnauthorized, GafferForbidden
  File "/tmp/ashald/.venvs/tmp-17f0a3d67a1d4821/lib/python2.7/site-packages/gaffer/httpclient/__init__.py", line 38, in <module>
    from .job import Job
  File "/tmp/ashald/.venvs/tmp-17f0a3d67a1d4821/lib/python2.7/site-packages/gaffer/httpclient/job.py", line 7, in <module>
    from ..process import ProcessConfig
  File "/tmp/ashald/.venvs/tmp-17f0a3d67a1d4821/lib/python2.7/site-packages/gaffer/process.py", line 18, in <module>
    from psutil.error import AccessDenied
ImportError: No module named error
```
Quick googling leads to ["psutil.error.py module was removed in 2.0.0 version"](http://stackoverflow.com/questions/22529900/no-module-psutil-error\#comment34544539_22530007)

Second attempt:
```bash
$ pip install "psutil<2"
...
Successfully installed psutil-1.2.1

$ gaffer --version
gaffer version 0.5.2
```

Looking at [setup.py](https://github.com/benoitc/gaffer/blob/master/setup.py#L62) in `master` there is version-unbounded dependency on `psutil`.

**Comment by SlyDen** [comment]
I confirm the problem exists... and your solution works

**Comment by benoitc** [comment]
will fix it until this we. I'm quite busy these days sorry :/

**Comment by SlyDen** [comment]
@benoitc no worries. You are doing great job.

**Comment by oca159** [comment]
i am havin the same issue, could you please update the repo?

**Comment by benoitc** [comment]
i will fix it during the we. i have been side tracked by... life
