### ISSUE TITLE
Isn't a directory

### ISSUE THREAD

**Issue by xenu256** [benoitc/gaffer#63]
/usr/local/anaconda/bin/gafferd -c /home/folder/gaffer.ini gives:

```text
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python3.6/site-packages/gaffer/gafferd/main.py", line 411, in run
    s = Server(args)
  File "/usr/local/anaconda/lib/python3.6/site-packages/gaffer/gafferd/main.py", line 105, in __init__
    raise RuntimeError("%r isn't a directory" % self.config_dir)
RuntimeError: '/home/folder/gaffer.ini' isn't a directory

error: '/home/folder/gaffer.ini' isn't a directory
```

**Comment by zhizhunbao** [comment]
i got the same error!~
