### ISSUE TITLE
AttributeError: 'HTTPClient' object has no attribute '_closed'

### ISSUE THREAD

**Issue by anuj9196** [benoitc/gaffer#65]
Gaffer version: **gaffer version 0.5.2**

I have a `Django 2.0` application deployed on `VPS` with virtual environment setup using `pipenv`.

At present, using this command to run the application from terminal in background.

    /root/.local/bin/pipenv run /home/user/.local/share/virtualenvs/app.application.com-IuTkL8w_/bin/gunicorn myapp.wsgi:application &

Now, I want to configure using `Procfile` and `gaffer`.

I added a file `Procfile` to root of the application directory with command

    web: gunicorn myapp.wsgi --log-file - --log-level debug

and trying to load it with `gaffer`

    $ cd myproject
    $ gaffer load Procfile

but it is giving error as

  

    Traceback (most recent call last):
      File "/usr/local/bin/gaffer", line 11, in <module>
        sys.exit(main())
      File "/usr/local/lib/python3.6/site-packages/gaffer/cli/main.py", line 252, in main
        cli.run()
      File "/usr/local/lib/python3.6/site-packages/gaffer/cli/main.py", line 193, in run
        config = Config(self.args)
      File "/usr/local/lib/python3.6/site-packages/gaffer/cli/main.py", line 87, in __init__
        api_key=api_key, **self.client_options)
      File "/usr/local/lib/python3.6/site-packages/gaffer/httpclient/server.py", line 22, in __init__
        super(Server, self).__init__(uri, loop=loop, **options)
      File "/usr/local/lib/python3.6/site-packages/gaffer/httpclient/base.py", line 86, in __init__
        self.client = HTTPClient(loop=loop)
      File "/usr/local/lib/python3.6/site-packages/gaffer/httpclient/base.py", line 42, in __init__
        self._io_loop = IOLoop(_loop=loop)
      File "/usr/local/lib/python3.6/site-packages/gaffer/tornado_pyuv.py", line 54, in __init__
        self._waker = Waker(self._loop)
      File "/usr/local/lib/python3.6/site-packages/gaffer/tornado_pyuv.py", line 28, in __init__
        self._async.unref()
    AttributeError: 'pyuv._cpyuv.Async' object has no attribute 'unref'
    Exception ignored in: <bound method HTTPClient.__del__ of <gaffer.httpclient.base.HTTPClient object at 0x7f96746c5b00>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/gaffer/httpclient/base.py", line 50, in __del__
        self.close()
      File "/usr/local/lib/python3.6/site-packages/gaffer/httpclient/base.py", line 54, in close
        if not self._closed:
    AttributeError: 'HTTPClient' object has no attribute '_closed'

**How to solve this `AttributeError: 'HTTPClient' object has no attribute '_closed'` error?**

**Comment by oolongtea** [comment]
I got the same issue. I tried other versions of tornado and pyuv but no luck. I ended up downgrading to gaffer v0.4.4.
